### ISSUE TITLE
Migrate from ReportHTML to PSWriteHTML?

### ISSUE THREAD

**Issue by c3rberus** [EvotecIT/PSWriteHTML#15]
I am currently using ReportHTML to generate a single HTML page that has a bunch of tabs with data feed from CSV exports. I would like to switch to using PSWriteHTML (to leverage Excel/CSV exports and speed), is there a upgrade path or can one swap one module for the other? 

I also noticed there is Dashimo as well, so which one should we use for future proofing? PSWriteHTML or Dashimo?

**Comment by PrzemyslawKlys** [comment]
Well - both PSWriteHTMl and Dashimo will be developed further. The idea behind Dashimo is that I can probably type out Dashimo dashboard from top of my head without even checking 

- Dashboard
- Section
- Panel
- Table 
- Tab

That's about it there is to know for now. PSWriteHTML has more features but those are often not connected with each other and adding things together may not be trivial. I often experiment with PSWriteHTML, change things and when I'm done I update Dashimo so that when I fixed new things, changed parameters Dashimo should be unaffected (as long as new features won't require changes). 


There is no direct path from ReportHTML to Dashimo or PSWriteHTML however it's like basic english to write in Dashimo. You need to forget about counting columns, opening and closing commands, defining tab headers. 

In Dashimo you simply do:

```
Dashboard -FilePath $PSScriptRoot\MyFile.html -Show {
     Section {
          Section {
                 Table 
          }
          Section {
                Table 
          }
     }
     Section {
          Panel {
             Table 
          } 
          Panel {
              Table 
          }
     }
}
```
I've typed that from top of my head. Please read Dashimo articles (there are 2 of them, showing how things are done). You basically type a command, open brace, and close brace when you're done. When you open a Section you can make it Invisible. Depending on how many columns you want you simply add as many Sections or Panels as you want to within a Section (or within Panel). It's a really simple concept once you grasp how it's built.

**Comment by c3rberus** [comment]
Ah okay gotcha, the last bit about dashimo being wrapper commands around PSWriteHTML registers. I'll need to experiment with both I think. Thanks for the quick reply.
