### ISSUE TITLE
Metadata options for DiagramNode

### ISSUE THREAD

**Issue by SumeshP** [EvotecIT/PSWriteHTML#152]
Is there a way to show metadata for a diagram node? i see a -textbox parameter, but looks like it is not implemented nor can i find any examples.
Use case is to show metadata like IP and other metadata for computers etc.

**Comment by PrzemyslawKlys** [comment]
You can use New-DiagramEvent to connect node with table. This way when you click a node it will select entry in a table (or tables). This allows you to push more data. Or you can push it via -Label in where you put all the required data but you need to set it up yourself.

**Comment by SumeshP** [comment]
thank you. will try out the table option.

**Comment by SumeshP** [comment]
Hi,
 tried the New-DiagramEvent and the Label options. However, both don't fit.
I want to show the metadata within the diagram on hover/click for example.
Label was the closer fit but it wouldn't allow newlines, everything shows up as a single line.
Is there any other way of doing this or do you plan something like this in future?

**Comment by PrzemyslawKlys** [comment]
Label does allow new lines as far as I know. You can also force label to accept markdown or HTML using `[ValidateSet('false', 'true', 'markdown', 'html')][string]$FontMulti`.

As you can see on examples VISJS offers a lot of customizations: https://visjs.github.io/vis-network/examples/ for example:
- https://visjs.github.io/vis-network/examples/network/labels/labelMultifont.html
- https://visjs.github.io/vis-network/examples/network/labels/multilineText.html

Also on my examples: https://evotec.xyz/creating-office-365-migration-diagram-with-powershell/ you can find I'm using labels with newlines
 ```
`n
```

But I believe I forgot to attach CSS for Vis-network library which will be fixed in next version. 

There's also what you want - instead of label there's a field for a node called title, which when hovered over will trigger popup. 

```html
{
                    "id": "3",
                    "label": "3",
                    'title': 'mooo'
}
```

I've not implemented it before, but I guess it shouldn't be too hard to implement. 

```powershell
New-HTML -TitleText 'My diagram' -Online -FilePath $PSScriptRoot\Example-Basic02.html {
    New-HTMLTabStyle -SlimTabs
    New-HTMLTab -Name 'Diagrams' -IconRegular arrow-alt-circle-left {
        New-HTMLSection -HeaderText 'Diagram - Defaults' -CanCollapse {
            New-HTMLPanel {
                New-HTMLDiagram {
                    New-DiagramNode -Label '1 test' -To '3', '6', '7' -ColorBackground Bisque
                    New-DiagramNode -Label '2' -To 'Przemyslaw Klys', '1 test'
                    New-DiagramNode -Label '3' -Title 'my new popup'
                    New-DiagramNode -Label 'Size based on name' -Shape database -Size 10 -Title "Long Line`nIn another line"
                    New-DiagramNode -Label 'Przemyslaw Klys'
                    New-DiagramNode -Label '6' -To 'Przemyslaw Klys' -ColorBorder Aquamarine -ColorBackground Yellow
                    New-DiagramNode -Label '7' -To 'Przemyslaw Klys' -ColorHighlightBackground Red -Shape diamond
                    New-DiagramNode -Label '8' -To 'Przemyslaw Klys' -ColorHoverBorder Yellow -Shape diamond
                }
            }
        }
    }
} -ShowHTML
```

I'll add this in the next version. I'll see if it's possible to use HTML inside title node.

**Comment by PrzemyslawKlys** [comment]
This is already added. Title + Label. 

You can check how it looks using experimental HTML inside node: https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example-Diagrams/Example-Basic.Experimental.ps1
