### ISSUE TITLE
0.0.153 WARNING: New-HTMLTable - Using SearchBuilder

### ISSUE THREAD

**Issue by theaxehax** [EvotecIT/PSWriteHTML#246]
When using GPOZaurr, PSWriteHTML version 0.0.153 doesn't work for me. If I use PSWriteHTML 0.0.148, my reports build okay, without warning.

WARNING: New-HTMLTable - Using SearchBuilder option and SearchBuilder button won't work properly. Only one will work. Disabling SearchBuiler.

**Comment by PrzemyslawKlys** [comment]
The warning is just a warning and doesn't impact on generation of GPOZaurr. It's added because if you add button SearchBuilder and SearchBuilder as an option only one works and the other may seem like a broken one. Hence the warning. 

![image](https://user-images.githubusercontent.com/15063294/122867429-c65c7500-d329-11eb-95da-fcfb71f8a467.png)

I just tested it and it works fine, and GPOZaurr will be updated to new PSWriteHTML sooner or later, but it shouldn't impact it in any way. Unless you're seeing something different?

**Comment by theaxehax** [comment]
Everything works, but the HTML report makes a person click through all the OK buttons. I've not been using the -online switch. What's the -online switch for? I've not figured out how to view the help documents. When I use Invoke-GPOZaurr -Type GPOBroken, I am given an HTML report to click through the OK buttons.

![image](https://user-images.githubusercontent.com/46203733/122969239-09324300-d352-11eb-8acf-f4710c14df30.png)
[](url)

**Comment by PrzemyslawKlys** [comment]
That's a weird message. It shouldn't be there for sure. I'll investigate. 

The -Online switch means HTML is smaller and cleaner because 90% of CSS/JS scripts are downloaded on demand from CDN sources - and it requires the person opening the file to be online. When you don't use Online all CSS/all JS are put into HTML which means the file can be easily 3MB+ just from the amount of CSS/JS code.

**Comment by PrzemyslawKlys** [comment]
I've fixed the issue. By accident I was using nightly version for offline usage and online version was using proper, production version that I tested which is a bit different than original.
