### ISSUE TITLE
new-htmltable id

### ISSUE THREAD

**Issue by robertfshort** [EvotecIT/PSWriteHTML#29]
When using new-htmltable it generates a random ID for that table and class appears to be limited in the style variable. Any way to have a parameter where I can set the table ID and/or class to be custom instead of the default operation?

**Comment by PrzemyslawKlys** [comment]
Yes, the ID is random and currently, there's no way to change it. It shouldn't be a problem to change it, although when one does so you would need to keep ID unique to different tables because DataTables functionality works on it. 

I'm curious thou why would you need it? Do you have something special or just have a different style in mind? Maybe it would be worth discussing including "that" style or your style as default if it's something nice? 

I'm no HTML/CSS/JS expert so if there's better, nicer way to make it prettier HTML I'm all about it.

**Comment by robertfshort** [comment]
I'm not an expert either, so I may be barking up a tree here when there is a better way of doing things... Specifically I was thinking about jquery. Say for instance I want two tables to look identical, but behave differently based upon jquery. I could do that with an ID or a class, but if I have 10 tables, and want half of them to respond a certain way to jquery and the other half to do something different, a custom class would be helpful.

As for a unique ID, perhaps a method to extract the ID after creation?

**Comment by PrzemyslawKlys** [comment]
So just that I get this correct, you want to extract ClassID I'm using and then apply some custom Jquery to it? So I guess you will be dealing directly with HTML/JS/JQUERY. 

Giving you an option to set ID seems simpler. Returning ID is not so simple because the return is usually HTML of a table. 

I would like to hear more about the "behave differently" because that seems useful if you have more "features" you could add to this project?

**Comment by robertfshort** [comment]
You may be reading a bit to much into that and I probably have a way around it. So lets say I have some controls on my website that pop off jquery scripts. I'm showing data pulled from a database, so these control can do things like, hide some tables, show other tables.

I suppose i could just put a wrapper around the table with an ID or class I know and then manipulate that instead of the table directly, which would work for my current use case.

But lets start thinking bigger... 

So from an executive's perspective, I get my dashboard page, I want to configure it to look a certain way:
Maybe this table needs every other line highlighted.
That table needs stoplight conditional formatting on this particular column
This other table should have every other row highlighted, but a different color from the first table.
etc...
Save a cookie so that next time I load the page it shows up with the same colored highlighting, column locations, etc. 

Me, the dashboard creator would need to be able to customize all of those things with the results of reading in that cookie and setting all those things using jquery on form load, which means I'd need table ID's and classes, and the table ID's would need to be unique and non-random so that they are the same every time the file gets generated by the system.

**Comment by PrzemyslawKlys** [comment]
Well, I haven't thought of using PSWriteHTML outside of the current feature set. I'll take a look at exposing the ID of Table if you wish. 

However, things like stopping conditional formatting, adding highlights every other row are something that should be on the roadmap for Table. I plan to mimic what is there for New-HTMLTableHeader to New-HTMLTableData or something that will allow the same thing but on data. So it will allow merge and style on rows including permanent conditional formatting.

**Comment by PrzemyslawKlys** [comment]
I have added this, hopefully, it will be good enough for you. Will be released when I'm done with other, new functionality.
