### ISSUE TITLE
Email outbound from Azure

### ISSUE THREAD

**Issue by RTTrickster** [EvotecIT/PSWriteHTML#331]
Hello, do you have any example command to send email via Azure please? Use case is via Azure Automation, initially thought we could send via smtp.office365.com but I believe port 25 is globally blocked in Azure. Does your module have a switch for port, as I believe port 587 works outbound from Azure? 

Currently standard config does not work, and does not error: 

`    EmailHeader {
        EmailFrom -Address "$SenderEmail"
        EmailTo -Addresses "$DestinationEmail"
        EmailServer -Server 'smtp.office365.com' -UserName $EmailUser -Password $EmailPass
        EmailSubject -Subject "Subject Line"
    }`

Thanks

**Comment by PrzemyslawKlys** [comment]
It does have port switch and few other settings.

![image](https://user-images.githubusercontent.com/15063294/182112778-ab3499c9-2d99-4b1f-91ab-7f365fd9c570.png)

You can find details on: https://evotec.xyz/meet-emailimo-new-way-to-send-pretty-emails-with-powershell/ which is integral part of PSWriteHTML since some time

Also: https://evotec.xyz/active-directory-dhcp-report-to-html-or-email-with-zero-html-knowledge/ shows how to use it with 587 port. 

You can also connect EmailBody directly with Mailozaurr and use Graph API to send emails.

https://evotec.xyz/mailozaurr-new-mail-toolkit-smtp-imap-pop3-with-support-for-oauth-2-0-and-graphapi-for-powershell/

I plan to add 'integrated" support for Mailozaurr into PSWriteHTML but lack time.

**Comment by RTTrickster** [comment]
Thanks for getting back to me, really appreciate it. I managed to get something working with your fantastic module and a free SendGrid account using hints from https://adamtheautomator.com/azure-send-email/. 

I hadn't seen your Mailozaurr previously but that looks really useful, especially Modern Authentication/oAuth support, I'm going to check this out. 

Thank you, these modules are amazing.

**Comment by PrzemyslawKlys** [comment]
Mailozaurr has a builtin a way to send using SendGrid. It expands on Send-EmailMessage, making it super easy.

Via SMTP:
https://github.com/EvotecIT/Mailozaurr/blob/8c39abb3946738f5213873b1bd95204792a83e52/Examples/Example-SendEmail-SendGrid01.ps1#L3-L10

Via API:
https://github.com/EvotecIT/Mailozaurr/blob/8c39abb3946738f5213873b1bd95204792a83e52/Examples/Example-SendEmail-SendGrid02.ps1#L3-L16
