### ISSUE TITLE
Nested Groups HTML report. 

### ISSUE THREAD

**Issue by Venom-Host** [EvotecIT/PSWriteHTML#375]
Question, not sure if this is possible or not using this module, but I'd like to setup a HTML file using the "Out-HtmlView" parameter that would show all of our nested groups with "Member of" & "Members". I know you have the module ADEssentials and if this is the easier method I'll do it, but just wanted it in the format in the screenshot. I was reading your article about "ADVANCED HTML REPORTING" wonder if it's possible to get this format using "ADVANCED HTML REPORTING". 

![image](https://user-images.githubusercontent.com/50363681/229567503-ae449a2c-6c83-44ad-9ffc-fcc93d30b4e9.png)

**Comment by PrzemyslawKlys** [comment]
It has nothing to do with PSWriteHTML and all to do with logic how you create your data to display in HTML. 

So from HTML perspective it's 5 lines of code. The trick is you have to prepare the data so that you have it in PowerShell format first. And that's going to be where the most work will go. 

ADEssentials get functions that can help with this, but still after you use Get-WinADGroupMember or Get-WinADGroupMemberOf you're gonna have to "convert" the output to what you want to see in the table. 

But again, nothing with HTML trick, more on the data side.
